# Generated by Django 3.2.6 on 2021-09-16 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0004_alter_customer_full_name'),
        ('product', '0003_product_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='wishlist',
            field=models.ManyToManyField(to='customers.Customer'),
        ),
    ]
