# Generated by Django 3.2.6 on 2021-10-14 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_auto_20210930_0108'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_review',
            field=models.BooleanField(default=False),
        ),
    ]
