# Generated by Django 3.2.6 on 2021-08-29 19:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('order', '0001_initial'),
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('star', models.PositiveSmallIntegerField(choices=[(5, 'Very satisfied'), (4, 'Satisfied'), (3, 'Neutral'), (2, 'Unsatisfied'), (1, 'Very unsatisfied')], default=5, verbose_name='stars')),
                ('reviewImage', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('feedback', models.TextField(help_text='Please share your feedback about the product was the product as described? What is the quality like?')),
                ('riderReview', models.TextField(blank=True, help_text='How was your overall experience with our rider?', null=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='customers.customer')),
                ('order_product', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='order.orderitem', verbose_name='order product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='product.product')),
            ],
            options={
                'verbose_name': 'Customer feedback',
                'ordering': ('-star',),
            },
        ),
    ]
