# Generated by Django 3.2.6 on 2021-11-03 10:24

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0004_auto_20211014_1426'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='reviewImage',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
