# Generated by Django 3.2.6 on 2021-08-29 19:36

import cloudinary.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('isPaid', models.BooleanField(default=False)),
                ('paid_date', models.DateField(auto_now_add=True)),
                ('isDelivered', models.BooleanField(default=False)),
                ('delivered_date', models.DateField(auto_now_add=True)),
                ('isCancelled', models.BooleanField(default=False)),
                ('isReturn', models.BooleanField(default=False)),
                ('order_created', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(blank=True, choices=[('Processing', 'Processing'), ('Shipped', 'Shipped'), ('Out for delivery', 'Out for delivery'), ('Delivered', 'Delivered'), ('archived', 'Archived - not available anymore')], max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_title', models.CharField(max_length=200)),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_discount_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('product_quantity', models.PositiveIntegerField(default=1)),
                ('product_image', cloudinary.models.CloudinaryField(max_length=255, verbose_name='image')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.order')),
            ],
        ),
    ]
