# Generated by Django 3.2.6 on 2021-11-03 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0008_auto_20211029_0044'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='delivered_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='order',
            name='paid_date',
            field=models.DateTimeField(),
        ),
    ]
